### PR TITLE
feat : add SAM2CameraPredictor

### PR DESCRIPTION
**Pull request by Gy920**
Run Segment Anything Model 2 on a live video stream

### CODE REVIEW

**Comment by a-krawciw** [comment]
Could you add a sample notebook showing this running on a video stream? Webcam or open cv VideoReader?

**Comment by AgentEXPL** [comment]
> Run Segment Anything Model 2 on a live video stream

@Gy920 How to use this? It may be great if an example is given.

**Comment by Gy920** [comment]
I have added the [notebook](https://github.com/Gy920/segment-anything-2/blob/da783ecb42b07f60626e855461e339be3707fe82/notebooks/camera_predictor_example.ipynb) and [instructions](https://github.com/Gy920/segment-anything-2/blob/da783ecb42b07f60626e855461e339be3707fe82/README.md#camera-prediction) on how to use it.

**Comment by AgentEXPL** [comment]
> I have added the [notebook](https://github.com/Gy920/segment-anything-2/blob/da783ecb42b07f60626e855461e339be3707fe82/notebooks/camera_predictor_example.ipynb) and [instructions](https://github.com/Gy920/segment-anything-2/blob/da783ecb42b07f60626e855461e339be3707fe82/README.md#camera-prediction) on how to use it.

@Gy920 In the examples of using SAM2CameraPredictor, the frame (which is in BGR?) from cap.read() may need to be converted to RGB first.

**Comment by Gy920** [comment]
> @Gy920 In the examples of using SAM2CameraPredictor, the frame (which is in BGR?) from cap.read() may need to be converted to RGB first.

My bad, I didn't catch that.

**Comment by AgentEXPL** [comment]
> > @Gy920 In the examples of using SAM2CameraPredictor, the frame (which is in BGR?) from cap.read() may need to be converted to RGB first.
> 
> My bad, I didn't catch that.

Never mind, it is still a great job after correction. I have checked that it works for streaming (frame-by-frame), but I found that the performance is worse than SAM2VideoPredictor.propagate_in_video() used in [.](https://github.com/facebookresearch/segment-anything-2/blob/main/notebooks/video_predictor_example.ipynb)   What's the difference between them in inference?

**Comment by Gy920** [comment]
> > > @Gy920 In the examples of using SAM2CameraPredictor, the frame (which is in BGR?) from cap.read() may need to be converted to RGB first.
> > 
> > 
> > My bad, I didn't catch that.
> 
> @Gy920 Never mind, it is still a great job after correction. I have checked that it works for streaming (frame-by-frame), but I found that the performance is worse than SAM2VideoPredictor.propagate_in_video() used in [video_predictor_example.ipynb.](https://github.com/facebookresearch/segment-anything-2/blob/main/notebooks/video_predictor_example.ipynb) . In some frames, part of the mask of the object is missing when using with SAM2CameraPredictor.track(), while it is good when using SAM2VideoPredictor.propagate_in_video(). What's the difference between them in inference?
> 
> In addition, only "add_new_points" is supported. Would it be possible to support "add_new_boxes" in SAM2CameraPredictor?


I have a hunch the issue might be tied to the [part](https://github.com/Gy920/segment-anything-2/blob/3bcea2dab3639fbc6ff7c4facdd2a712bca2aed8/sam2/sam2_camera_predictor.py#L545)  simplified during implementation. That could explain the drop in tracking performance.And thanks for the heads-up on add_new_boxes, I'll definitely add that to SAM2CameraPredictor.

I'm a bit swamped at the moment, but I'll carve out some time to dig into this issue and get it sorted as soon as possible.

**Pull request closed without merging**
